### ISSUE TITLE
Add pre-deploy comment to PR that is updated with post-deploy info

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-cd#202]
## Background

It would be nice to let users know that a deployment/redeployment is actually in progress via comment, before it happens. 

This would utilize the `access-nri/actions/comment` action once https://github.com/ACCESS-NRI/actions/issues/19 is complete. 

## Implementation Details

I already had part of a solution while testing:

```yaml
  pre-deploy-notifier:
    name: Pre Deploy Notifier
    needs:
      - defaults
    runs-on: ubuntu-latest
    outputs:
      comment-url: ${{ steps.comment.outputs.comment-url }}
    steps:
      - name: PR Comment Notifier
        id: comment
        uses: access-nri/actions/.github/actions/comment@main
        with:
          number: ${{ inputs.pr }}
          message: |
            :rocket: [Currently Deploying](${{ env.RUN_URL }}) `${{ inputs.model }}` Prerelease as `${{ needs.defaults.outputs.prerelease-version }}` with commit ${{ needs.defaults.outputs.head-sha }}

            This comment will be updated with the status of the deployment(s).

```
