### ISSUE TITLE
Variants are stripped from root spec due to prerelease modifications

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/build-cd#260]
See https://github.com/ACCESS-NRI/ACCESS-ESM1.6/pull/70#issuecomment-2767665510

The variants are being stripped from the root spec because the Prerelease spack.yaml modifications replace the spec with only the root spec name. So:

```yaml
spack:
  specs:
    - access-om2@git.2025.04.0 +debug
```
becomes:
```yaml
spack:
  specs:
    - access-om2
```
instead of:
```yaml
spack:
  specs:
    - access-om2 +debug
```
