### ISSUE TITLE
Support general software build and deployment

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/build-cd#276]
### Introduction

There are tools associated with ACCESS models that ACCESS-NRI needs to build and deploy in a trusted and reliable manner on HPC targets. Python tools are generally deployed in `conda` environments, and in some cases non-python tools are also deployed in `conda` environments. There are limitations to `conda` and in some cases where we want stand-alone tools `spack` might be a better fit.

### Proposal

The proposal is to re-use the `build-cd` infrastructure to build and deploy software: similar software would be grouped together in a single environment (`spack.yaml`).

This use case is covered by the existing infrastructure, except for some assumptions about there being a "top-level" SBR.

**Comment by aidanheerdegen** [comment]
There is a test-case here:

https://github.com/ACCESS-NRI/model-tools/pull/1

The `model-tools` repo was created from the model-deployment repo template with modifications to the `spack.yaml` based on this PR

https://github.com/ACCESS-NRI/ACCESS-OM3/pull/45

**Comment by aidanheerdegen** [comment]
The above test case works to build and deploy to pre-release:

```
$ module use /g/data/vk83/prerelease/modules
$ module load fre-nctools/pr1-5
$ echo $PATH
/g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-2021.10.0/fre-nctools-git.2024.05_2024.05-i4evfp27rfqcaksu6xh7ck43gbs535fm/bin:/home/502/aph502/code/git/git-subrepo/lib:/apps/git/2.37.3/bin:/apps/netcdf/4.7.3/bin:/apps/ncview/2.1.7/bin:/home/502/aph502/bin:/opt/pbs/default/bin:/opt/nci/bin:/opt/bin:/opt/Modules/v4.3.0/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/pbs/default/bin:.
$ ls /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64/intel-2021.10.0/fre-nctools-git.2024.05_2024.05-i4evfp27rfqcaksu6xh7ck43gbs535fm/bin
check_mask           make_hgrid              nc_null_check
combine-ncc          make_land_domain        plevel.sh
combine_restarts     make_quick_mosaic       remap_land
cp_river_vars        make_regional_mosaic    river_regrid
cr_lake_files        make_remap_file         rmv_parallel_rivers
decompress-ncc       make_simple_hydrog.csh  runoff_regrid
fregrid              make_solo_mosaic        scatter-ncc
iceberg_comb.sh      make_topog              timavg
is-compressed        make_vgrid              timavg.csh
list_ncvars.csh      mppnccombine            transfer_to_mosaic_grid
list_ncvars.sh       mppncscatter
make_coupler_mosaic  ncexists
```

Current problems:

- Instructions say to do `model-tools/pr1-5` because that is the name I specified in the environment, but that is incorrect.
- Even though we have multiple tools, I think they'll be versioned with the top level package (so replace `pr1-5` with the top level package version). Is that right?

**Comment by aidanheerdegen** [comment]
I tried to [add `model-tools` to the projection](https://github.com/ACCESS-NRI/model-tools/pull/1/commits/a518d43f61124bb7d604f564faafda5be512af15)
```diff
diff --git a/spack.yaml b/spack.yaml
index d1bb62d..8b6ddaf 100644
--- a/spack.yaml
+++ b/spack.yaml
@@ -28,4 +28,4 @@ spack:
         include:
           - fre-nctools
         projections:
-          fre-nctools: '{name}/2024.05'
+          fre-nctools: 'model-tools/{name}/2024.05'
```

but the [checks don't like it](https://github.com/ACCESS-NRI/model-tools/actions/runs/15176077584/job/42676498638?pr=1#step:12:8):
```
Error: Some projections in the spack manifest don't match.
```

**Comment by aidanheerdegen** [comment]
Specifying just a version (not `git.version`) in the `spec` works

https://github.com/ACCESS-NRI/model-tools/pull/1#issuecomment-2902877801

but I suspect that it will fail for non-draft PRs.

**Comment by aidanheerdegen** [comment]
I tried adding a second sec (`gh`) to test how that would work. 

```yaml
spack:
  specs:
    - fre-nctools@2024.05 %intel@2021.10.0
    - gh@2.43.1
  packages:
    netcdf-c:
      require:
        - '@4.9.2'
    netcdf-fortran:
      require:
        - '@4.6.1'
  view: true
  concretizer:
    unify: true
  modules:
    default:
      tcl:
        include:
          - fre-nctools
          - gh
        projections:
          fre-nctools: '{name}/2024.05'
          gh: '{name}/2.43.1'
```

The [checks complain](https://github.com/ACCESS-NRI/model-tools/actions/runs/15203177510/job/42760861251?pr=1#step:12:1)
```
Error: Some projections in the spack manifest don't match.
```
I also tried using the same version as `fre-nctools` for `gh`, but that also fails.

**Comment by aidanheerdegen** [comment]
That's weird. I removed the `gh` projections altogether (to test the build) and I still got an error about projections not matching

https://github.com/ACCESS-NRI/model-tools/actions/runs/15204737090/job/42765237019?pr=1

Is that because I've got the compiler in the `spec` @CodeGat ?

```yaml
spack:
  specs:
    - fre-nctools@2024.05 %intel@2021.10.0
    - gh@2.43.1
```
